### ISSUE TITLE
Make sure the man page warns that fonts are not embedded by default

### ISSUE THREAD

**Issue by jidanni** [ssimms/pdfapi2#33]
For https://rt.cpan.org/Ticket/Display.html?id=130041 just make sure the man page warns that fonts are not embedded by default, so when sharing a document, the receiving party (e.g., potential employer) might not be able to read it.

**Comment by ssimms** [comment]
Added a note to the CJKFont class in 2.042 saying that it doesn't create portable PDF files and redirecting people to use TrueType/OpenType fonts instead.
