### ISSUE TITLE
Creating a PDF destroys existing file 

### ISSUE THREAD

**Issue by sciurius** [ssimms/pdfapi2#41]
Creating a PDF object immedeately writes PDF header to disk. 

````
$pdf = PDF::API2->new( file => "tl.pdf" );
````
I am not sure this is intentional, I'd expect that the file is not created/written until `save` is performed.

**Comment by ssimms** [comment]
Yes, that's intentional and documented.  Writing the file immediately allows for lower memory usage, though I don't recall if that's actually happening in the current code.

If you don't want to overwrite the file immediately, wait to pass the filename until you call `save`.
