### ISSUE TITLE
Viewer preference non_full_screen_page_mode returns invalid value

### ISSUE THREAD

**Issue by sciurius** [ssimms/pdfapi2#50]
By default, PDF::API2 provides the value `use_none` for viewer preference `non_full_screen_page_mode`. However, this value is not understood by the `viewer_prefrences` method.

````
my $pdf = PDF::API2->new;
my %i = $pdf->viewer_preferences;
warn("viewer_preferences non_full_screen_page_mode = ",
     $i{non_full_screen_page_mode}, "\n");
$pdf->viewer_preferences(%i);

````

**Comment by ssimms** [comment]
`viewer_preferences` will now correctly return the same values that it accepts (minus the `use_` prefix).
