### ISSUE TITLE
Extra "59" in LICENSE

### ISSUE THREAD

**Issue by mtelka** [ssimms/pdfapi2#59]
The `LICENSE` file in the [source tarball](https://cpan.metacpan.org/authors/id/S/SS/SSIMMS/PDF-API2-2.044.tar.gz) contains these lines:

```
Copyright (C) 1991, 1999 Free Software Foundation, Inc. 59
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
```

Please note there is extra `59` at the end of first line above when compared to https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt.

I'm not sure where the `LICENSE` file comes from (it is not in git), but it would be great if the extra `59` is removed from it.

Thank you.

**Comment by ssimms** [comment]
Please make a pull request for the Software::License distribution to get this fixed.  The file in question is here:
https://github.com/Perl-Toolchain-Gang/Software-License/blob/main/lib/Software/License/LGPL_2_1.pm

Incidentally, it looks like the extra "59" has gone unnoticed for at least 15 years.

**Comment by mtelka** [comment]
Thanks for the pointer: https://github.com/Perl-Toolchain-Gang/Software-License/pull/84
